[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_build.partitions = huge_app.csv
lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43
build_flags =
    -DUSER_SETUP_LOADED=1
    -DILI9341_DRIVER=1
    -DTFT_WIDTH=240
    -DTFT_HEIGHT=320
    -DTFT_MISO=13
    -DTFT_MOSI=11
    -DTFT_SCLK=12
    -DTFT_CS=10
    -DTFT_DC=46
    -DTFT_RST=-1
    -DTFT_BL=45
    -DTFT_BACKLIGHT_ON=HIGH
    -DLOAD_GLCD=1
    -DSPI_FREQUENCY=40000000
